import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Lang = "ar" | "en" | "fr" | "es";

export const LANGUAGES: { code: Lang; name: string; nativeName: string; dir: "rtl" | "ltr"; flag: string }[] = [
  { code: "ar", name: "Arabic", nativeName: "العربية", dir: "rtl", flag: "🇸🇦" },
  { code: "en", name: "English", nativeName: "English", dir: "ltr", flag: "🇬🇧" },
  { code: "fr", name: "French", nativeName: "Français", dir: "ltr", flag: "🇫🇷" },
  { code: "es", name: "Spanish", nativeName: "Español", dir: "ltr", flag: "🇪🇸" },
];

const translations: Record<Lang, Record<string, string>> = {
  ar: {
    // Welcome
    welcome_title: "مرحباً بك في Game Hub",
    welcome_subtitle: "اختر لغتك المفضلة للبدء",
    welcome_start: "ابدأ اللعب",
    select_language: "اختر اللغة",

    // Index
    app_title: "🎮 Game Hub",
    app_subtitle: "ألعاب كلاسيكية بتصميم أنيق",
    footer_text: "Classic Games Collection v1.0",
    xo_title: "XO",
    xo_subtitle: "تيك تاك تو",
    chess_title: "شطرنج",
    chess_subtitle: "Chess",
    ludo_title: "لودو",
    ludo_subtitle: "Ludo",
    tournament_title: "بطولة",
    tournament_subtitle: "Tournament",

    // Settings
    settings: "الإعدادات",
    sound_effects: "مؤثرات صوتية",
    background_music: "موسيقى خلفية",
    language: "اللغة",

    // Common game
    back: "رجوع",
    reset: "إعادة",
    local_play: "محلي",
    vs_ai: "ضد الذكاء",
    online: "أونلاين",
    easy: "سهل",
    medium: "متوسط",
    hard: "صعب",
    your_turn: "دورك",
    opponent_turn: "دور الخصم",
    you_win: "فزت! 🎉",
    you_lose: "خسرت!",
    draw_result: "تعادل!",
    new_game: "لعبة جديدة",
    game_settings: "إعدادات اللعبة",
    sound_on: "صوت",
    sound_off: "صامت",
    players: "اللاعبون",
    score: "النتيجة",

    // Chess specific
    white_turn: "دور الأبيض",
    black_turn: "دور الأسود",
    check: "كش!",
    checkmate_white: "كش مات! الأبيض يفوز",
    checkmate_black: "كش مات! الأسود يفوز",
    stalemate: "تعادل (جمود)",
    draw_game: "تعادل",
    ai_thinking: "الذكاء يفكر...",
    board_theme: "شكل اللوحة",
    piece_theme: "شكل القطع",
    difficulty: "الصعوبة",
    game_mode: "وضع اللعب",
    undo: "تراجع",
    promote_to: "ترقية إلى",
    theme_wood: "خشبي",
    theme_marble: "رخامي",
    theme_plain: "كلاسيكي",
    theme_emerald: "زمردي",
    piece_classic: "كلاسيكي",
    piece_neo: "حديث",
    piece_staunton: "ستاونتن",
    piece_minimal: "بسيط",

    // XO specific
    grid_size: "حجم الشبكة",
    symbols: "الرموز",
    x_wins: "فوز X",
    o_wins: "فوز O",
    draws: "تعادل",
    x_turn: "دور X",
    o_turn: "دور O",
    x_wins_result: "فاز X! 🎉",
    o_wins_result: "فاز O! 🎉",

    // Ludo specific
    roll_dice: "ارمِ النرد",
    color_red: "الأحمر",
    color_green: "الأخضر",
    color_yellow: "الأصفر",
    color_blue: "الأزرق",
    turn_of: "دور",
    wins: "يفوز! 🎉",
    num_players: "عدد اللاعبين",
    piece_style: "شكل القطع",

    // Tournament
    tournament: "بطولة",
    connected_players: "اللاعبون المتصلون",
    waiting_players: "في انتظار اللاعبين...",
    setup_tournament: "إعداد البطولة",
    players_per_match: "عدد اللاعبين في كل مباراة",
    auto_group: "تقسيم تلقائي",
    group: "مجموعة",
    start_tournament: "ابدأ البطولة!",
    tournament_finished: "انتهت البطولة!",
    champion: "البطل",
    round: "الدور",
    final: "النهائي",
    playing: "جارية...",
    n_players: "لاعبين",
    n_groups: "مجموعة",
  },
  en: {
    welcome_title: "Welcome to Game Hub",
    welcome_subtitle: "Choose your preferred language to start",
    welcome_start: "Start Playing",
    select_language: "Select Language",

    app_title: "🎮 Game Hub",
    app_subtitle: "Classic games with elegant design",
    footer_text: "Classic Games Collection v1.0",
    xo_title: "XO",
    xo_subtitle: "Tic Tac Toe",
    chess_title: "Chess",
    chess_subtitle: "Strategy Game",
    ludo_title: "Ludo",
    ludo_subtitle: "Board Game",
    tournament_title: "Tournament",
    tournament_subtitle: "Compete",

    settings: "Settings",
    sound_effects: "Sound Effects",
    background_music: "Background Music",
    language: "Language",

    back: "Back",
    reset: "Reset",
    local_play: "Local",
    vs_ai: "vs AI",
    online: "Online",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    your_turn: "Your turn",
    opponent_turn: "Opponent's turn",
    you_win: "You win! 🎉",
    you_lose: "You lose!",
    draw_result: "Draw!",
    new_game: "New Game",
    game_settings: "Game Settings",
    sound_on: "Sound",
    sound_off: "Muted",
    players: "Players",
    score: "Score",

    white_turn: "White's turn",
    black_turn: "Black's turn",
    check: "Check!",
    checkmate_white: "Checkmate! White wins",
    checkmate_black: "Checkmate! Black wins",
    stalemate: "Stalemate",
    draw_game: "Draw",
    ai_thinking: "AI thinking...",
    board_theme: "Board Theme",
    piece_theme: "Piece Theme",
    difficulty: "Difficulty",
    game_mode: "Game Mode",
    undo: "Undo",
    promote_to: "Promote to",
    theme_wood: "Wood",
    theme_marble: "Marble",
    theme_plain: "Classic",
    theme_emerald: "Emerald",
    piece_classic: "Classic",
    piece_neo: "Neo",
    piece_staunton: "Staunton",
    piece_minimal: "Minimal",

    grid_size: "Grid Size",
    symbols: "Symbols",
    x_wins: "X Wins",
    o_wins: "O Wins",
    draws: "Draws",
    x_turn: "X's turn",
    o_turn: "O's turn",
    x_wins_result: "X wins! 🎉",
    o_wins_result: "O wins! 🎉",

    roll_dice: "Roll Dice",
    color_red: "Red",
    color_green: "Green",
    color_yellow: "Yellow",
    color_blue: "Blue",
    turn_of: "Turn:",
    wins: "wins! 🎉",
    num_players: "Players",
    piece_style: "Piece Style",

    tournament: "Tournament",
    connected_players: "Connected Players",
    waiting_players: "Waiting for players...",
    setup_tournament: "Setup Tournament",
    players_per_match: "Players per match",
    auto_group: "Auto Group",
    group: "Group",
    start_tournament: "Start Tournament!",
    tournament_finished: "Tournament Finished!",
    champion: "Champion",
    round: "Round",
    final: "Final",
    playing: "Playing...",
    n_players: "players",
    n_groups: "group(s)",
  },
  fr: {
    welcome_title: "Bienvenue sur Game Hub",
    welcome_subtitle: "Choisissez votre langue préférée pour commencer",
    welcome_start: "Commencer à jouer",
    select_language: "Choisir la langue",

    app_title: "🎮 Game Hub",
    app_subtitle: "Jeux classiques au design élégant",
    footer_text: "Classic Games Collection v1.0",
    xo_title: "XO",
    xo_subtitle: "Morpion",
    chess_title: "Échecs",
    chess_subtitle: "Jeu de stratégie",
    ludo_title: "Ludo",
    ludo_subtitle: "Jeu de plateau",
    tournament_title: "Tournoi",
    tournament_subtitle: "Compétition",

    settings: "Paramètres",
    sound_effects: "Effets sonores",
    background_music: "Musique de fond",
    language: "Langue",

    back: "Retour",
    reset: "Réinitialiser",
    local_play: "Local",
    vs_ai: "vs IA",
    online: "En ligne",
    easy: "Facile",
    medium: "Moyen",
    hard: "Difficile",
    your_turn: "Votre tour",
    opponent_turn: "Tour de l'adversaire",
    you_win: "Vous gagnez ! 🎉",
    you_lose: "Vous perdez !",
    draw_result: "Égalité !",
    new_game: "Nouvelle partie",
    game_settings: "Paramètres du jeu",
    sound_on: "Son",
    sound_off: "Muet",
    players: "Joueurs",
    score: "Score",

    white_turn: "Tour des blancs",
    black_turn: "Tour des noirs",
    check: "Échec !",
    checkmate_white: "Échec et mat ! Les blancs gagnent",
    checkmate_black: "Échec et mat ! Les noirs gagnent",
    stalemate: "Pat",
    draw_game: "Égalité",
    ai_thinking: "L'IA réfléchit...",
    board_theme: "Thème du plateau",
    piece_theme: "Style des pièces",
    difficulty: "Difficulté",
    game_mode: "Mode de jeu",
    undo: "Annuler",
    promote_to: "Promouvoir en",
    theme_wood: "Bois",
    theme_marble: "Marbre",
    theme_plain: "Classique",
    theme_emerald: "Émeraude",
    piece_classic: "Classique",
    piece_neo: "Néo",
    piece_staunton: "Staunton",
    piece_minimal: "Minimal",

    grid_size: "Taille de la grille",
    symbols: "Symboles",
    x_wins: "Victoires X",
    o_wins: "Victoires O",
    draws: "Égalités",
    x_turn: "Tour de X",
    o_turn: "Tour de O",
    x_wins_result: "X gagne ! 🎉",
    o_wins_result: "O gagne ! 🎉",

    roll_dice: "Lancer le dé",
    color_red: "Rouge",
    color_green: "Vert",
    color_yellow: "Jaune",
    color_blue: "Bleu",
    turn_of: "Tour :",
    wins: "gagne ! 🎉",
    num_players: "Joueurs",
    piece_style: "Style des pièces",

    tournament: "Tournoi",
    connected_players: "Joueurs connectés",
    waiting_players: "En attente de joueurs...",
    setup_tournament: "Configurer le tournoi",
    players_per_match: "Joueurs par match",
    auto_group: "Groupement auto",
    group: "Groupe",
    start_tournament: "Démarrer le tournoi !",
    tournament_finished: "Tournoi terminé !",
    champion: "Champion",
    round: "Tour",
    final: "Finale",
    playing: "En cours...",
    n_players: "joueurs",
    n_groups: "groupe(s)",
  },
  es: {
    welcome_title: "Bienvenido a Game Hub",
    welcome_subtitle: "Elige tu idioma preferido para comenzar",
    welcome_start: "Empezar a jugar",
    select_language: "Seleccionar idioma",

    app_title: "🎮 Game Hub",
    app_subtitle: "Juegos clásicos con diseño elegante",
    footer_text: "Classic Games Collection v1.0",
    xo_title: "XO",
    xo_subtitle: "Tres en raya",
    chess_title: "Ajedrez",
    chess_subtitle: "Juego de estrategia",
    ludo_title: "Ludo",
    ludo_subtitle: "Juego de mesa",
    tournament_title: "Torneo",
    tournament_subtitle: "Competición",

    settings: "Ajustes",
    sound_effects: "Efectos de sonido",
    background_music: "Música de fondo",
    language: "Idioma",

    back: "Volver",
    reset: "Reiniciar",
    local_play: "Local",
    vs_ai: "vs IA",
    online: "En línea",
    easy: "Fácil",
    medium: "Medio",
    hard: "Difícil",
    your_turn: "Tu turno",
    opponent_turn: "Turno del oponente",
    you_win: "¡Ganaste! 🎉",
    you_lose: "¡Perdiste!",
    draw_result: "¡Empate!",
    new_game: "Nueva partida",
    game_settings: "Ajustes del juego",
    sound_on: "Sonido",
    sound_off: "Silencio",
    players: "Jugadores",
    score: "Puntuación",

    white_turn: "Turno de las blancas",
    black_turn: "Turno de las negras",
    check: "¡Jaque!",
    checkmate_white: "¡Jaque mate! Ganan las blancas",
    checkmate_black: "¡Jaque mate! Ganan las negras",
    stalemate: "Tablas (ahogado)",
    draw_game: "Empate",
    ai_thinking: "La IA está pensando...",
    board_theme: "Tema del tablero",
    piece_theme: "Estilo de piezas",
    difficulty: "Dificultad",
    game_mode: "Modo de juego",
    undo: "Deshacer",
    promote_to: "Promover a",
    theme_wood: "Madera",
    theme_marble: "Mármol",
    theme_plain: "Clásico",
    theme_emerald: "Esmeralda",
    piece_classic: "Clásico",
    piece_neo: "Neo",
    piece_staunton: "Staunton",
    piece_minimal: "Mínimo",

    grid_size: "Tamaño de cuadrícula",
    symbols: "Símbolos",
    x_wins: "Victorias X",
    o_wins: "Victorias O",
    draws: "Empates",
    x_turn: "Turno de X",
    o_turn: "Turno de O",
    x_wins_result: "¡X gana! 🎉",
    o_wins_result: "¡O gana! 🎉",

    roll_dice: "Lanzar dado",
    color_red: "Rojo",
    color_green: "Verde",
    color_yellow: "Amarillo",
    color_blue: "Azul",
    turn_of: "Turno:",
    wins: "¡gana! 🎉",
    num_players: "Jugadores",
    piece_style: "Estilo de piezas",

    tournament: "Torneo",
    connected_players: "Jugadores conectados",
    waiting_players: "Esperando jugadores...",
    setup_tournament: "Configurar torneo",
    players_per_match: "Jugadores por partida",
    auto_group: "Agrupación auto",
    group: "Grupo",
    start_tournament: "¡Iniciar torneo!",
    tournament_finished: "¡Torneo finalizado!",
    champion: "Campeón",
    round: "Ronda",
    final: "Final",
    playing: "Jugando...",
    n_players: "jugadores",
    n_groups: "grupo(s)",
  },
};

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  dir: "rtl" | "ltr";
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: "ar",
  setLang: () => {},
  t: (key) => key,
  dir: "rtl",
  isRTL: true,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("game-hub-lang");
    return (saved as Lang) || "ar";
  });

  const setLang = (newLang: Lang) => {
    setLangState(newLang);
    localStorage.setItem("game-hub-lang", newLang);
  };

  const dir = LANGUAGES.find((l) => l.code === lang)?.dir || "rtl";
  const isRTL = dir === "rtl";

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations["en"]?.[key] || key;
  };

  useEffect(() => {
    document.documentElement.lang = lang;
    document.documentElement.dir = dir;
  }, [lang, dir]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir, isRTL }}>
      {children}
    </LanguageContext.Provider>
  );
};
